### PR TITLE
Bugfix/nullref

### PR DESCRIPTION
**Pull request by jsundra**
- Pushes ancient change that I used in the current dlls, but never pushed apparently.
- Fixes an annoying bug where calling `Log.Info(this, <something that's a null ref>)` would cause an exception in the logger itself. Now just logs `Null` instead.
- Changes the version to 2020.8, and updates the namespace to Enklu! (There will be a gross PR coming for dependencies soon, don't worry ;))

### CODE REVIEW

**Review by gdamron — APPROVED** [review]
and 👍 on namespace update

**Comment by thegoldenmule** [comment]
Excellent work @jsundra -- this is really primo stuff.

**Comment by gdamron** [comment]
where'd that troll come from?!

**Comment by thegoldenmule** [comment]
https://www.bing.com/search?q=polygonal+pronunciation

**Review by ShannonKalei — APPROVED** [review]
🎉

**Pull request merged**
